# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2abad4c8b33de9621733c95681ea28fa78d221d6be9098a1db113ee23973f5fe8af4d7fb11eef5ef31bed825d27e0af79328dad33467b9606ee87c0022f77dff

test:
  secret_key_base: 5abf9be03d38bd681c9e2566e40e0ae0ed4bc7753d6c9c363f3d222571b17d56f2c57e94078eb2f8e2b624b96c66ff2c02ac1fd3908263efe37b8c7da31d9f39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
